data:extend({
  {
    type = "bool-setting",
    default_value = true,
    name = "vtm-showModgui",
    setting_type = "runtime-per-user",
    order = "a",
  },
  {
    type = "bool-setting",
    default_value = false,
    name = "vtm-name-new-station",
    setting_type = "runtime-global",
    order = "a",
  },
  {
    type = "string-setting",
    name = "vtm-new-station-name",
    setting_type = "runtime-global",
    default_value = "Unused Station",
    order = "a",
  },
  {
    type = "string-setting",
    name = "vtm-depot-names",
    setting_type = "runtime-global",
    default_value = "depot,shuttle,unused",
    order = "bb",
  },
  {
    type = "string-setting",
    name = "vtm-refuel-names",
    setting_type = "runtime-global",
    default_value = "refuel",
    order = "c",
  },
  {
    type = "string-setting",
    name = "vtm-requester-names",
    setting_type = "runtime-global",
    default_value = "requester,delivery",
    order = "d",
  },
  {
    type = "string-setting",
    name = "vtm-provider-names",
    setting_type = "runtime-global",
    default_value = "provider,mine,field,production",
    order = "e",
  },
  {
    type = "bool-setting",
    name = "vtm-p-or-r-start",
    setting_type = "runtime-global",
    default_value = true,
    order = "f",
  },
  {
    type = "bool-setting",
    name = "vtm-dont-read-depot-stock",
    setting_type = "runtime-global",
    default_value = false,
    order = "g",
  },
  {
    type = "bool-setting",
    name = "vtm-show-undef-warning",
    setting_type = "runtime-global",
    default_value = true,
    order = "h",
  },
  {
    type = "bool-setting",
    name = "vtm-force-surface-visible",
    setting_type = "runtime-global",
    default_value = false,
    order = "h",
  },
  {
    type = "int-setting",
    name = "vtm-limit-auto-refresh",
    setting_type = "runtime-global",
    minimum_value = 0,
    maximum_value = 1000,
    default_value = 50,
    order = "i",
  },
  {
    type = "int-setting",
    name = "vtm-history-length",
    setting_type = "runtime-global",
    minimum_value = 10,
    maximum_value = 1000,
    default_value = 20,
    order = "j",
  },
  {
    type = "bool-setting",
    name = "vtm-dismiss-tool",
    setting_type = "runtime-per-user",
    default_value = false,
    order = "k",
  },
  {
    type = "string-setting",
    name = "vtm-stock-wire-color",
    setting_type = "runtime-global",
    default_value = "Both",
    allowed_values = { "Both", "Red", "Green" },
    allow_blank = false,
    order = "l",
  },
})
